---
name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Executing python code
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.1"
          architecture: "x64"
      - run: python choise.py
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/innerdayd:latest
  self:
    name: run on self-hosted runner
    runs-on: self-hosted
    needs: super-lint
    steps:
      - name: pull image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/innerdayd:latest
      - name: run image
        run: docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/innerdayd:latest
